### ISSUE TITLE
Application freezes when opening the Second screen in MVVM+Coordinator example on iOS 17

### ISSUE THREAD

**Issue by YaroslavErmolaev** [ozontech/SUINavigation#1]
### Description:
1. **Summary:** In the MVVM+Coordinator example, the application freezes (infinite creation of `SecondView`) when trying to open the Second screen. This issue occurs only on iOS 17.
2. **Steps to Reproduce:**
   1. Launch the application.
   2. Tap the "toFirst" button to navigate to the First screen.
   3. Tap the "toSecond" button to navigate to the Second screen.
3. **Expected Behavior:** The application should successfully navigate to the Second screen without freezing.
4. **Actual Behavior:** The application freezes and gets stuck in an infinite loop of creating `SecondView` instances.
5. **Additional Information:** This issue has been observed only on iOS 17.

**Labels:** bug, iOS 17

**Comment by sofbix** [comment]
Thanks a lot for your detailed description.
Your issue of example mades possible to find out the issue in the base component.
Problem with cyclic update of environment object from navigation item modifier.
Fix will be released in 1.10.1.
See Changes in 1.10.1 for more information.
