### ISSUE TITLE
Xcode console always report a warning

### ISSUE THREAD

**Issue by yikibug** [ozontech/SUINavigation#2]
Do not put a navigation destination modifier inside a "lazy” container, like `List` or `LazyVStack`. These containers create child views only when needed to render on screen. Add the navigation destination modifier outside these containers so that the navigation stack can always see the destination. There's a misplaced `navigationDestination(isPresented:destination:)` modifier presenting `Optional<xxxx>`. It will be ignored in a future release.

**Comment by sofbix** [comment]
So, yes.
I forgot to add in the component description how to use the modifier `.navigation(..)`, and I corrected it:

- Note that `.navigation(..)` applies to all content in the view being navigated from. This modifier should not be allowed to apply to child elements of that view, such as childs of ListView, LazyView and each others. Better use `.navigation(..)` below of all content of that view as in the code below.


Also have to added example for illustration mistakes using `.navigation(..)`.
Incorrect that:

```swift

/// Incorrect implementation of the list when navigation is focused on each list item
struct FalseListView: View {

    var array = ListView.elements

    @State
    var isDetailsShow = false

    var body: some View {
        List(array, id: \.self) { item in
            Button {
                isDetailsShow = true
            } label: {
                Text(item)
                    .navigation(isActive: $isDetailsShow) {
                        DetailsView(text: item)
                    }
            }
        }
        .padding(0)
        .navigationTitle("Elements")
    }
}

```

Correct that:

```swift

/// Сorrect implementation of the list when navigation is focused on the entire screen and not on its individual elements
struct TrueListView: View {

    var array = ListView.elements

    @State
    var detailsItem: String? = nil

    var body: some View {
        List(array, id: \.self) { item in
            Button {
                detailsItem = item
            } label: {
                Text(item)
            }
        }
        .padding(0)
        .navigationTitle("Elements")
        .navigation(item: $detailsItem) { item in
            DetailsView(text: item)
        }
    }
}

```

For more information you can get [example](https://github.com/ozontech/SUINavigation/tree/main/Example/ListDetais).
Does what I wrote cover this task? Can it be closed or do you have a different case?

**Comment by yikibug** [comment]
In your example, If put ListView() in TabView,  Xcode console still report a warning above.

```
import SwiftUI
import SUINavigation

@main
struct ListDetailsApp: App {
    var body: some Scene {
        WindowGroup {
            NavigationViewStorage {
                TabView {
                    ListView()
                }
            }
        }
    }
}
```

And I found the warning relates to the following source code, delete by testing ```.modifier(modifier)``` no warning will be reported, but you can't actually delete it.

```
//
//  View.swift
//
//
//  Created by Sergey Balalaev on 26.01.2024.
//

import SwiftUI

public extension View {

    /// Facade target with optimisation
    /// for revert just edit to call self.modifier(modifier)
    @inlinable public func navigationModifier<T: ViewModifier>(_ modifier: T) -> some View
    {
        self.backgroundModifier(modifier)
    }

    /// Modifier with optimisation, but can down performance on first showing becase use EmptyView
    @inlinable func backgroundModifier<T: ViewModifier>(_ modifier: T) -> some View
    {
        self.background (
            EmptyView()
                 .modifier(modifier)
        )
    }
}
```

**Comment by sofbix** [comment]
Thanks for fully Answer.
I'am reseach about this problem. The root of them you have from NavigationStack + navigationDestination:

``` swift

@main
struct ListDetailsApp: App {
    @State private var path: [String] = []

    var body: some Scene {
        WindowGroup {
            NavigationStack(path: $path) {
                TabView {
                    Tab("Received", systemImage: "tray.and.arrow.down.fill") {
                        EmptyView()
                            .navigationDestination(for: String.self) { route in
                                switch route {
                                case ".View1":
                                    Text("View1")
                                case ".View2":
                                    Text("View2")
                                default:
                                    Text("default")
                                }
                            }

                    }
                }
            }
        }
    }
}

```

It seems like TabView is also perceived as a "lazy” container, like `List` or `LazyVStack`. This bug is reproduced from iOS 18 [here](https://stackoverflow.com/questions/78752796/navigation-issue-in-swiftui-ios-18-skipping-a-page).
I promise to think about how to fix it.
Thanks a lot for this case.

**Comment by sofbix** [comment]
Apple recommend use the TabView outside of the NavigationStack [here](https://forums.developer.apple.com/forums/thread/756647)
But we just use the TabView inside of the NavigationStack the same as you. It's more convenient. Continue to research...

**Comment by yikibug** [comment]
Thank you for fixing the Xcode warning issue in the latest version of v1.11.0, I hope this project will get better and better
